version: "3.9"

services:
  db:
    # image: mariadb:10.11.5  # raise an issue with timers
    image: mariadb:10.8.2
    container_name: mariadb_container
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=shield_project_db
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
    volumes:
      - ~/mariadb_data:/var/lib/mysql
      - ./database/:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    # healthcheck:
    #   test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3

  users: # users api
    depends_on:
      db:
        # condition: service_healthy  # require db healthcheck 
        condition: service_started
    image: dummyfcd/users_container:0.0.1
    ports:
      - target: 8008
        published: 8008
        protocol: tcp
        mode: host
