version: "3.9"
services:
  bdd:
    image: dummyfcd/bdd_container:0.0.1
    volumes:
      - ~/data:/mounted_data_container_side
  data:
    image: dummyfcd/data_container:0.0.1
    volumes:
      - ~/data:/mounted_data_container_side
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host

