version: "3.9"
services:
  bdd:
    image: dummyfcd/raw_data_container:0.0.1
#    container_name: bdd
    volumes:
      - ~/data:/mounted_data_container_side
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
        mode: host

#      environment:
#      LOG: 1
