name: Run Tests

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary
  pull_request:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  test:
    runs-on: ubuntu-latest  # You can change the operating system if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming you have a requirements.txt file

    - name: Run unit tests
      run: |
        python -m unittest test_api.py  # Run your unit tests
