name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest  # Vous pouvez choisir un autre système d'exploitation si nécessaire

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker images & run Docker containers in background
      run: docker-compose -f src/docker/docker-compose-dev.yml up --detach
