name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image for unit tests
      run: docker build -t my_unit_tests tests/  # Use the path to the tests/ directory

    - name: Run unit tests
      run: docker run my_unit_tests
