name: Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOCKER_REGISTRY: fabricecharraud/shield

jobs:
  test:
    runs-on: ubuntu-latest  # Vous pouvez choisir un autre système d'exploitation si nécessaire

    services:
      docker:
        image: docker:latest
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create ~/mariadb_data
      run: mkdir ~/mariadb_data

    - name: Build Docker images & run Docker containers in background
      run: docker-compose -f src/docker/docker-compose-dev.yml up --detach
